spring:
  #数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mytools?useUnicode=true&characterEncoding=utf8
    username: root
    password: glt123
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT1FROMDUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    logSlowSql: true
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/os/
  #thymeleaf配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    cache: false
  #热部署的配置
  devtools:
   restart:
    enabled: true
    additional-paths: src/main/java
#mybatis的配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.james.crm_int.entity
#日志的设置
logging:
  level:
    com:
      woniuxy: debug
shiro:
  hash-algorithm-name: md5
  hash-iterations: 1024
  login-url: /login.html
  unauthorized-url: /login.html
  anon-urls:
    - /login.html
    - /login
    - /resources/** #静态文件放行
  authc-urls:
    - /**